spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.123.55/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:/log/      #默认生成spring.log文件
#  file: D:/log/sell.log/ #sell创建文件
#  level:
#    com.tghoul.LoggerTest: debug